### ISSUE TITLE
".." when code and data are separated

### ISSUE THREAD

**Issue by bladerunnerwalrus** [r-lib/here#105]
My question is related to this: https://stackoverflow.com/questions/76686047/best-practice-for-the-r-here-package-without-rstudio 

My code and data are in separate folders ,thus here() goes to code folder by default, where no data is present. Just curious whether usage of here("..", "data", "mydata.csv") is advised? If not, what should be done? 

Apologies, if this was asked before.

**Comment by krlmlr** [comment]
Thanks. This looks like a valid use case, but if you and your collaborators don't use Windows, perhaps consider creating a symbolic link to `../data` from your project directory? This makes the project self-contained again.

**Comment by bladerunnerwalrus** [comment]
Thanks! I'll try it with my next project. For now I kept the project file in project folder, but moved code to code folder, allowing to use `here("data"...)`.
