### ISSUE TITLE
`here::i_am()` not working with RStudio

### ISSUE THREAD

**Issue by KleinWurm** [r-lib/here#106]
I faced this issue while playing around with `here::i_am()` and found https://github.com/r-lib/here/issues/73#issue-947905396 which is very related but does point the exact same problem.

**Problem: `here::i_am()` returns default RStudio working directory (even when set to `~` in global options).**

![image](https://github.com/r-lib/here/assets/90380874/3b711814-df52-48e6-8b4b-bb0967f316cf)

With here 1.0.1, RStudio 2024.04.0+735 and R version 4.3.2.

**Example:**

Structure of the folder:

```
 test
    .here
     test_script.R
```

And the content of `test_script.R` is:
```r
here::i_am(path = "test_script.R")
```
Console output when `test_script.R` is executed from RStudio:

```r
> here::i_am(path = "test_script.R")
Erreur : Could not find associated project in working directory or any parent directory.
- Path in project: test_script.R
- Current working directory: C:/Users/Username/Documents
Please open the project associated with this file and try again.
```
It shows a similar error if I try
```r
here::i_am(path = ".here")
```

However, if I run the script from Visual Studio, I get the expected output:

```r
> here::i_am(path = ".here") # also works with "test_script.R" instead of ".here"
here() starts at C:/Users/[path]/test
```
This suggests an incompatibility of `here::i_am()` with RStudio.

**Comment by krlmlr** [comment]
It works for me when I have opened a project in RStudio. What does `getwd()` show?

**Comment by KleinWurm** [comment]
@krlmlr sorry for my late reply, I tried again with RStudio RStudio 2024.04.1+748 " and R version 4.3.2 and it seems that the `here::i_am()` function now works in RStudio with the same behavior as in Visual Studio.

From RStudio, I get the same output as from Visual Studio:

```r
> here::i_am(path = "test_script.R") 
here() starts at C:/Users/[path]/test
```

And `getwd()` returns `C:/Users/[path]/test`.
