### ISSUE TITLE
fs integration?

### ISSUE THREAD

**Issue by hadley** [r-lib/here#11]
[fs](https://github.com/r-lib/fs) is a new package (soon to be submitted to CRAN) for handling file-system operations. It might be nice to add some here integration so that you can do (e.g.) `here::here_list(..)` as a shortcut for `fs::dir_list(here::here(...))`.

**Comment by hadley** [comment]
Alternatively, fs could provide the here integration, by suggesting `here` and providing `path_here()`

**Comment by krlmlr** [comment]
I like the idea of a `path_here()` function.

**Comment by krlmlr** [comment]
Not sure this is worth pursuing.
