### ISSUE TITLE
Plyr package conflict

### ISSUE THREAD

**Issue by LTzavella** [r-lib/here#17]
Thank you for this package, excellent use for reproducible scripts! 

There is a conflict with the **plyr** package (see here {plyr}). That happens only if you load the 'here' package before 'plyr'- so the solution is easy- just thought I'd put it out there!

**Comment by krlmlr** [comment]
Thanks. There's a note regarding lubridate in https://here.r-lib.org/reference/here.html, need to extend it to include other packages too.

**Comment by krlmlr** [comment]
I added a section to the ["Getting started" article](https://here.r-lib.org/articles/here.html), feedback welcome.
