### ISSUE TITLE
Change active `here()` directory

### ISSUE THREAD

**Issue by robertamezquita** [r-lib/here#19]
Currently doesn't seem to change the `here()` output when changing directories - which is fine by design, however, if you need to change folders/projects there's no way to force a change in the `here()` reference.

```{r}
here()  # outputs: /path/to/project_root
setwd('path/to/new_project_root')
here()  # still outputs: /path/to/project_root

## proposed:
change_here('/path/to/new_project_root')
here()  # outputs: /path/to/new_project_root
```

Might there be room for a `change_here()` function that forces a change in directory or something similar? (I'd prefer a reference to Oasis' "Be Here Now" but that might be too long).

**Comment by krlmlr** [comment]
I have a separate `.Rproj` file for each project, and just open that when I want to switch projects. (Usually I also have more than one RStudio instance open at any given time.)

Restarting the R session also might work.

I'd like to keep the interface of *here* as simple as possible.

**Comment by leungi** [comment]
I second this request, mainly to workaround a well-documented issue with RStudio running slow in network drive vs. local.

Currently, I set up .Rproj locally, while accessing everything else (e.g., scripts, data) from network. It really improves RStudio run time significantly.

Hope @krlmlr will consider.

Thanks!

**Comment by StevenHibble** [comment]
Here's my (hacky) workaround. Not sure if this breaks anything, but it seems good so far. 

`change_here <- function(new_path){
  new_root <- here:::.root_env
  
  new_root$f <- function(...){file.path(new_path, ...)}
  
  assignInNamespace(".root_env", new_root, ns = "here")
}`

**Comment by krlmlr** [comment]
I'm hesitant to provide a supported entry point, there are other good reasons to start afresh. I documented a workaround that features `unloadNamespace()` in the ["Getting started" article](https://here.r-lib.org/articles/here.html), feedback welcome.

**Comment by krlmlr** [comment]
`here::i_am()` offers a new way to declare the project root, each script and report declares its own path relative to the project root. Does this help with your scenario?

Read more at: https://here.r-lib.org/articles/here.html#declare-the-location-of-the-current-script-1

**Comment by leungi** [comment]
> `here::i_am()` offers a new way to declare the project root, each script and report declares its own path relative to the project root. Does this help with your scenario?
> 
> Read more at: https://here.r-lib.org/articles/here.html#declare-the-location-of-the-current-script-1

Thanks for  this @krlmlr .

Hope you don't take this negatively, but it doesn't help my use case 😅.

The framework I have in mind is as follow:

- allow .Rproj to be defined anywhere (in my case, local drive vs. network drive to improve RStudio IDE performance)
- allow access to folders and files in network drive, via a _link_ generated via a function in `here`
