### ISSUE TITLE
here does not seem to be there

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/here#20]
Having a problem accessing the site:

![image](https://user-images.githubusercontent.com/2800934/39711390-3cd35d44-51e5-11e8-9557-0ae22fa35097.png)

Also, I could not pass up the chance to write the title for this issue 🤓

**Comment by jennybc** [comment]
I just ran across this myself, because the usethis docs link to the non-existent page. Is here slated to get a pkgdown site with an r-lib-based URL soon?

**Comment by jennybc** [comment]
@batpigandme Do you think you could help get this site and the one for rprojroot back up and running? I think it may have been just the transfer to r-lib that upset the apple cart.

**Comment by jennybc** [comment]
In fact, this appears to be already working: https://r-lib.github.io/here/

**Comment by batpigandme** [comment]
Yep, should be up now: http://here.r-lib.org/

**Comment by jennybc** [comment]
Something's a little sad up here in upper left 🤔, but I am already happy because I've got a working and stable link now:

<img width="551" alt="screen shot 2018-06-20 at 12 42 01 pm" src="https://user-images.githubusercontent.com/599454/41680775-73d7ea8e-7487-11e8-8b1d-ea5e32223252.png">

**Comment by batpigandme** [comment]
Yeah, I think that's because of a problem with the old pkgdown/tidytemplate, should be better in https://github.com/r-lib/here/pull/22

**Comment by ijlyttle** [comment]
Here appears to be there now, thanks!

(please forgive this gif)

![image](https://media.giphy.com/media/yp0PhkxxCPB6g/giphy.gif)
