### ISSUE TITLE
Feature request: reset the starting point of `here()` automatically to the directory containing `.here` when `set_here()` is used

### ISSUE THREAD

**Issue by prosoitos** [r-lib/here#28]
Thanks a ton for the package. I love it and am following in Jenny's path in advocating its use instead of `setwd()`.

My issue is closely related to jennybc/here_here#3 and #24.

Problem:

You need to create a `.here` file in a directory because it isn't big nor important enough to justify doing version control on it. But that directory is nested in another one which has a `.something` file that `here` will use to set the "project" root. Now, using `set_here()` will create the `.here` file just fine, but `here` has already been set and there is no way to update it unless restarting the R process (which creates a very awkward workflow and impairs automation).

As mentioned in other issues re-running `library(here)` (which wouldn't be a great solution anyway) has no effect. And I even tried running `here::set_here()` *before* running `library(here)`, but that does not work either. Reloading R is the only solution.

Suggestion:

`set_here()` does what it should and work great when `here` hasn't been set on a wrong target (due to something higher in the path than the intended project root), but fails when a wrong target was found. Having a function that would automatically run while using `set_here()` to reset here to the location of the `.here` file that has just been created would be more robust and cover situations such as the one I am describing.

**Comment by prosoitos** [comment]
Note: when one creates a `.here` file, it is obviously with the intention of using it as a marker of the project root. So having `here` reset any project root it might have set upon being loaded to the location of that newly created `.here` file seems sensible and that's why I feel that this should be done automatically by the function `set_here()` rather than by another function that one would have to run in situations such as the one I described above.

**Comment by prosoitos** [comment]
Noobie's alert: this might be a naive comment and I could be totally wrong on this. But I feel that `here` must run some function to set the location of the project root when it is first loaded (or used by `here::set_here()`). So my feature request might just be a question of automatically re-running that function which already exists as soon as the `.here` file is created.

**Comment by robertamezquita** [comment]
Totally agreed with this, just want to say that sometimes the `here` package miscalculates the root the first time around (especially when setting up a new package/analysis), and sometimes having to restart an R session is onerous especially on a cluster (sometimes start the R session in the wrong place, and then lose X11 connectivity, and so on..tl;dr restarting R is a pain).

**Comment by tnoomah** [comment]
I found this issue thread because I was also trying to find a way to reset here mid session. I thought I'd comment for anyone else who finds this in the future because I was able to find a workaround. 

Start with your first .here path location
```
library(here)
```
> here() starts at C:/Users/gtheot/Documents


Then to reset, detach here, reset the working directory with setwd, and when you reload here, you'll be in the new directory
```
detach("package:here", unload=TRUE)
setwd("C:/Users/gtheot/Desktop")
library(here)
```
>here() starts at C:/Users/gtheot/Desktop

**Comment by reidwil** [comment]
@tnoomah does this fix it for future referencing of `here()`? If not, having to manually setwd every time to get the right `here()` path is now completely defeating this package's purpose

**Comment by tnoomah** [comment]
@reidwil when you detach here, set the working directory manually and reload here, you create a new .here file which will be the point of reference for here going forward in your session. You only have to manually setwd when you want to change the location of your .here file, after that you can use here like you normally would.

**Comment by krlmlr** [comment]
After `set_here()` you will need to start a new R session. You could also get away with `unloadNamespace("here")` if necessary. I documented this in the ["Getting started" article](https://here.r-lib.org/articles/here.html), feedback welcome.
