### ISSUE TITLE
Error in here - unused arguments

### ISSUE THREAD

**Issue by rbhuey** [r-lib/here#30]
I have a sub-directory "results".  When trying to read in a file from there, here sometimes works but often I get the following error message.  Nothing pops up on a google search.

tmp <- read_csv(here("results", "soilSUM.csv"))
Error in here("results", "soilSUM.csv") : 
  unused arguments ("results", "soilSUM.csv")

**Comment by krlmlr** [comment]
Thanks. Can you please try loading the {conflicted} package and running your code?

```
library(conflicted)
tmp <- read_csv(here("results", "soilSUM.csv"))
```

**Comment by rbhuey** [comment]
Kirill

Thank you!!  This must be a common problem, at least for those (like me) who load packages as follows:

	suppressWarnings(suppressMessages(library(lubridate))) 

Henceforth, I’ll stop doing that.  And I’ve set the  conflict+prefer to “here”.

Incidentally, “here” makes life much easier.  Thanks very much.   And I’m sure I’ll use “conflicted” on other occasions (other packages).

Should I close this on github?

with best wishes

Ray



Error: [conflicted] `here` found in 2 packages.
Either pick the one you want with `::` 
* lubridate::here
* here::here
Or declare a preference with `conflict_prefer()`
* conflict_prefer("here", "lubridate")
* conflict_prefer("here", "here")
> conflict_prefer("here", "here")
[conflicted] Will prefer here::here over any other package

**Comment by NoushinN** [comment]
I also have a new error using this package:

```
> library(here)
> here()
[1] "2019-06-17 22:12:53 PDT"
Warning message:
'here' is deprecated; use 'now' instead. Deprecated in version '1.5.6'. 
```
