### ISSUE TITLE
Conflict with lubridate::here()

### ISSUE THREAD

**Issue by jasonpott** [r-lib/here#37]
I have been trying to use here() within a project where I am importing data from an online Research database. 

I have then attempt to use here() within the saveRDS() function e.g.

`saveRDS(mydfname, file= here("02_data", "mydfname.rda"))`

This would ensure I have a local copy of the data for if I need to work on the project but I am offline. 

When I execute the code my data import runs as expected, but the saveRDS function returns the following error

`Error in here("02_data", "mydfname.rda") : 
  unused arguments ("02_data", "mydfname.rda")`

I have searched the issues listed here and online but have not found any other reports of this issue. 

My work around is that I am having to input the file directory in full for saveRDS() but here is working for file calls using readRDS() and source()

I may be missing something simple so excuse my ignorance if that is the case.

**Comment by krlmlr** [comment]
It looks like `lubridate::here()` is the core of the problem. We could use better documentation for the causes and possible solutions:

``` r
library(here)
#> here() starts at /tmp/RtmpcFhpW6/reprex44ae186a5ab3
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:here':
#> 
#>     here
#> The following object is masked from 'package:base':
#> 
#>     date

here("02_data", "mydfname.rda")
#> Error in here("02_data", "mydfname.rda"): unused arguments ("02_data", "mydfname.rda")
```

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I can propose two solutions: {conflicted} or `here::here()`

## conflicted

``` r
library(here)
#> here() starts at /tmp/RtmpcFhpW6/reprex44ae6dbee44f
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:here':
#> 
#>     here
#> The following object is masked from 'package:base':
#> 
#>     date
library(conflicted)

here("02_data", "mydfname.rda")
#> Error: [conflicted] `here` found in 2 packages.
#> Either pick the one you want with `::` 
#> * lubridate::here
#> * here::here
#> Or declare a preference with `conflict_prefer()`
#> * conflict_prefer("here", "lubridate")
#> * conflict_prefer("here", "here")
conflict_prefer("here", "here")
#> [conflicted] Will prefer here::here over any other package
here("02_data", "mydfname.rda")
#> [1] "/tmp/RtmpcFhpW6/reprex44ae6dbee44f/02_data/mydfname.rda"
```

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

## `here::here()`

``` r
library(here)
#> here() starts at /tmp/RtmpcFhpW6/reprex44ae3787be7b
library(lubridate)
#> 
#> Attaching package: 'lubridate'
#> The following object is masked from 'package:here':
#> 
#>     here
#> The following object is masked from 'package:base':
#> 
#>     date

here::here("02_data", "mydfname.rda")
#> [1] "/tmp/RtmpcFhpW6/reprex44ae3787be7b/02_data/mydfname.rda"
```

<sup>Created on 2020-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
