### ISSUE TITLE
could we have sme option(s) to "clean" the file path ?

### ISSUE THREAD

**Issue by moodymudskipper** [r-lib/here#39]
`here()` keeps consecutive separators, and it allows mixing slashes and backslashes. It would be nice to  be able to specify an option "standardize" or likewise, to get a clean path with no duplicate separators and only forward slashes (or only the operator system's "prefered" separator).

**Comment by krlmlr** [comment]
There's `fs::path_tidy()` and also `normalizePath()`, not sure we need to enforce it here.
