### ISSUE TITLE
How to change the location of here() when switching Rscripts in one session?

### ISSUE THREAD

**Issue by Sebaristoteles** [r-lib/here#41]
I am bit puzzled about the way here() breaks the workflow.
When I use several R scripts from different projects in one Session (e.g. RStudio) and I switch between them it seems not to be possible to reset the location of here(). I would have to close the session and start a new one. This is obviously corrupting the workflow since in e.g. RStudio you might have objects in the environment that you have calculated for a long time, saving takes time and additional effort, etc.

If there is no way to do switch the location of here in one session, I would like to request this feature.
Otherwise, the here package is completely useless for my purposes.

**Comment by kevin-a-ryan** [comment]
I agree this impacts workflow.  There seem to be other related issues open. 
- Unloading and reloading the here package resets here() without requiring a new R session.
- Assigning here() outputs as different objects to be referenced in different scripts might help.
- Using a .Rproj upstream of all the scripts your working with may reduce the need to change here().

**Comment by krlmlr** [comment]
Thanks @kevin-a-ryan. Unloading is the way to go, I documented it in the "Getting started" vignette.

**Comment by krlmlr** [comment]
`here::i_am()` offers a new way to declare the project root, each script and report declares its own path relative to the project root. Does this help with your scenario?

Read more at: https://here.r-lib.org/articles/here.html#declare-the-location-of-the-current-script-1
