### ISSUE TITLE
Links on CRAN page are no more correct because here has moved to r-lib

### ISSUE THREAD

**Issue by cderv** [r-lib/here#46]
Hi, 

I believe since `here` as been moved to r-lib 2 years ago (https://github.com/r-lib/here/commit/19ef731aaf02df181609ac7fc4f947f33bfdc26b), there has been no CRAN release since because the CRAN page still contains the urls pointing to old documentation site and repo. See https://cran.r-project.org/web/packages/here/index.html

I often go to the CRAN page to find the link of the pkgdown website, and currently, it is 404 because not the correct one and not redirection. I may be the only one but I think it worth sharing this.

**Comment by krlmlr** [comment]
Thanks. About to send a new CRAN release.
