### ISSUE TITLE
here does not appear to find the package directory when run from inside the tests folder

### ISSUE THREAD

**Issue by yogat3ch** [r-lib/here#49]
I am encountering issues with `here::here()` not being able to find the root directory of a package when it's called from inside the *tests/testthat* folder. 
I have a *.here* file, a *DESCRIPTION* file, and an *Rproj* file two levels up from the *tests/testthat* as one might expect, but `dr_here` indicates the following:

```
- contains a file `.here`
- contains a file matching `[.]Rproj$` with contents matching `^Version: ` in the first line
- contains a file `DESCRIPTION` with contents matching `^Package: `
- contains a file `remake.yml`
- contains a file `.projectile`
- contains a directory `.git`
- contains a file `.git` with contents matching `^gitdir: `
- contains a directory `.svn`
```

It seems like it's not traversing up the tree to the proper parents given this output. 
The following does work to find the root directory however:

```
rprojroot::find_root_file(criterion = rprojroot::has_file("DESCRIPTION"))
```

**Comment by krlmlr** [comment]
Thanks. It should work in tests (run by `devtools::test()`), but known to fail in `R CMD check` . Can you confirm?

**Comment by yogat3ch** [comment]
It fails in `devtools::check`, confirmed. That's what clued me into the issue. It also fails at the console, that's when I opened the issue.

**Comment by yogat3ch** [comment]
To work in R CMD check, maybe it could start in the working directory and use `list.files(pattern "^DESCRIPTION$", recursive = TRUE)` until it finds the lowest level directory that meets the criteria?

**Comment by yogat3ch** [comment]
Something like this:

```
#' @title find_path
#' @description Finds a file or directory by traversing the directory tree.
#' @param .fn The case-sensitive regex for the file passed to \code{\link[base]{list.files}}.
#' @return The objects are loaded into the specified environment. 
#' @examples
#' find_path("Rminor.RData")
#' @export

find_path <- function(.fn) {
  .path <- "."
  .fs <- list.files(.path, pattern = .fn, all.files = TRUE, full.names = TRUE, recursive = TRUE)
  while (length(.fs) < 1) {
    .path <- file.path("..", .path)
    .fs <- list.files(.path, pattern = .fn, all.files = TRUE, full.names = TRUE, recursive = TRUE)
  }
  return(.fs)
}
```

**Comment by krlmlr** [comment]
`R CMD check` creates its own very specific structure -- the tests are top-level, with no `DESCRIPTION` above them. That's the reason for `rprojroot::is_testthat` :

``` r
rprojroot::is_testthat
#> Root criterion: directory name is `testthat` (also look in subdirectories: `tests/testthat`, `testthat`)
```

<sup>Created on 2020-10-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Would that work for you? To get started, use `find_root(is_testthat)` .

**Comment by yogat3ch** [comment]
Boom, that's it - somehow I missed `is_testthat`! Thank you for the tip! Much appreciative of your time and willingness to help!
