### ISSUE TITLE
Re-licensing here

### ISSUE THREAD

**Issue by hadley** [r-lib/here#50]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/r-lib/here/graphs/contributors). @nzgwynn, @sharlagelfand, would you permit us to re-license here with the MIT license? If so, please comment "I agree" below.

* [x] [@nzgwynn](https://github.com/r-lib/here/commits?author=nzgwynn)  
* [x] [@sharlagelfand](https://github.com/r-lib/here/commits?author=sharlagelfand)

**Comment by nzgwynn** [comment]
I agree
