### ISSUE TITLE
Should `here` be idempotent?

### ISSUE THREAD

**Issue by pitakakariki** [r-lib/here#70]
Often I'm passing filenames through multiple function call, and sometimes I'm extra-careful and wrap that filename in `here` in multiple places.

```
> "data/mydata.csv"
[1] "data/mydata.csv"
> 
> here("data/mydata.csv")
[1] "D:/projects/thisproject/data/mydata.csv"
> 
> here(here("data/mydata.csv"))
[1] "D:/projects/thisproject/D:/projects/thisproject/data/mydata.csv"
```

Probably a little dangerous to pattern-match the first part of the string, but maybe an attribute could be set?

**Comment by pitakakariki** [comment]
Sorry it's been a long week. Should have installed the latest version before posting.

**Comment by krlmlr** [comment]
Glad it works for you, thanks for the heads-up!
