### ISSUE TITLE
Doesn't escape paths containing spaces.

### ISSUE THREAD

**Issue by robdotson** [r-lib/here#71]
The here::here() command returns a string without escaped spaces in paths which contain them.

```
flights_path <- here::here("data", "flights.csv")
> 
> flights_path
[1] "/Volumes/2021/Spring/CSCI E 497/CTP Proposal/data/flights.csv"
> 
```

Which should be: 

"/Volumes/2021/Spring/CSCI\ E\ 497/CTP\ Proposal/data/flights.csv"

**Comment by krlmlr** [comment]
Thanks. Quoting or escaping spaces and other special characters is relevant e.g. if you pass the path as a command-line argument to a shell. In many other cases this does more harm than good:

``` r
writeLines("Hi!", "a b.txt")
readLines("a b.txt")
#> [1] "Hi!"
readLines("a\\ b.txt")
#> Warning in file(con, "r"): cannot open file 'a\ b.txt': No such file or
#> directory
#> Error in file(con, "r"): cannot open the connection
```

<sup>Created on 2021-04-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This seems out of scope for {here}.

Can you please take this to https://community.rstudio.com, with an explanation of your use case? (You might want to read https://www.tidyverse.org/help/ first to maximize your chances of getting a good answer.)

**Comment by robdotson** [comment]
The use case is including any files (in my case csv files) that are in the project path to be used in a script. Unfortunately, there are many, many, many directories on macOS which have spaces in their names, and there is no restriction or norm against doing so, so not escaping spaces causes this to break pretty much anywhere it is used. Normally one would simply use the standard file tools and escape the directories paths, so I was surprised when I inherited a large code base and this wasn't happening under the hood in the here command. Escaping spaces in path/file names is the norm any time files are opened unless you're using one of the NSFile APIs, which R is not.

----
ROB DOTSON (バトー．ドットソン)
Founder and CEO
***@***.***
+1 646 407 6262

**Comment by krlmlr** [comment]
What happens when you run the reproducible example from my last post on your system?

**Comment by robdotson** [comment]
writeLines("Hi!", "a b.txt")
#> Error in file(con, "wt"): cannot open the connection
readLines("a b.txt")
#> Warning in file(con, "r"): cannot open file 'a b.txt': No such file or directory

----
ROB DOTSON (バトー．ドットソン)
Founder and CEO
***@***.***
+1 646 407 6262

**Comment by krlmlr** [comment]
Thanks.

:open_mouth:

Can you please confirm: `writeLines("Hi!", "ab.txt")` works, `writeLines("Hi!", "a b.txt")` doesn't, and `writeLines("Hi!", "a\\ b.txt")` works again?

**Comment by robdotson** [comment]
﻿It appears that spaces need to be escaped but other "path" characters cannot be used at all. Maybe this is an apfs thing? 
﻿
writeLines("Hi!", "a\ b.txt")
readLines("a\ b.txt")
#> [1] "Hi!"
writeLines("Hi!", "ab.txt")
readLines("ab.txt")
#> [1] "Hi!"
writeLines("Hi!", "a\\b.txt")
#> Error in file(con, "wt"): cannot open the connection
readLines("a\\b.txt")
#> Warning in file(con, "r"): cannot open file 'a b.txt': No such file or directory
writeLines("Hi!", "a\:b.txt")
#> Error in file(con, "wt"): cannot open the connection
readLines("a\:b.txt")
#> Warning in file(con, "r"): cannot open file 'a b.txt': No such file or directory
----
ROB DOTSON (バトー．ドットソン)
Founder and CEO
***@***.***
+1 646 407 6262
