### ISSUE TITLE
Can here() give the short path in windows, to make compatible with use cases where a path with spaces will fail?

### ISSUE THREAD

**Issue by markbneal** [r-lib/here#82]
There are some examples where a path with spaces is returned by here(), but the path doesn't work for that application.  Windows has a "short path" option that results in paths with no spaces. Can here() provide the short path as an option? 

Here is an example in R where path with a space fails, but can manually be altered to the short path, and then works. 
[https://stackoverflow.com/q/72610074/4927395](https://stackoverflow.com/q/72610074/4927395)

**Comment by krlmlr** [comment]
Thanks. This feels out of scope for `here()`, can you use `utils::shortPathName()` manually? You could implement a wrapper for yourself:

```r
here_short <- function(...) {
  shortPathName(here(...))
}
```

**Comment by markbneal** [comment]
Thanks for the pointer, I'll try that. Whatever search terms I was looking for were not working for me!
