### ISSUE TITLE
Help: use Here with write.csv

### ISSUE THREAD

**Issue by nmidde** [r-lib/here#84]
Hi there,
I would like to us Here in write.csv to write the file with the following settings. I tried few ways but wasn't able to do it. Appreciate your help. 

write.csv(tmp,file=paste(projPath,"/data/output",format(Sys.Date(),"%Y%b%d"),".csv",sep=""),quote=F,row.names = F,na=".")

**Comment by krlmlr** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximize your chances of getting a good answer.)

Have you tried `here("data/output")` instead of `paste(...)` ?

**Comment by nmidde** [comment]
Thanks for reply. Will do.
